import { StyleSheet } from "react-native";
import colors from "../../../../color";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white'
  },
  header: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  body: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  main: {
    width: "80%",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    shadowColor: "black",
    shadowRadius: 20,
    alignItems: "center",
  },
  abas: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  aba: {
    width: "50%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F2F2F2",
    padding: 7,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 15,

  },
  abaSelecionada: {
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: colors.primary,
    // backgroundColor: "#B3DFE7",
  },
  textAba: {
    fontWeight: "bold",
    fontSize: 18,
    color: colors.primary,
  },
  modal: {
    width: "100%",
    alignItems: "center",
    borderBottomLeftRadius: 10,
    borderBottomEndRadius: 10,
    shadowRadius: 20,
    elevation: 15,
    backgroundColor: "#F2F2F2",
  },
  titulo_cadastro: {
    marginTop: 10,
    marginBottom: 10,
    fontWeight: "bold",
    fontSize: 32,
    color: colors.primary,
  },
  texto_cadastro: {
    marginTop: 10,
    marginBottom: 10,
    fontWeight: "bold",
    fontSize: 20,
    color: colors.primary,
  },
  input: {
    height: 50,
    width: "80%",
    backgroundColor: "white",
    borderRadius: 5,
    padding: 10,
    marginTop: 10,
    marginBottom: 10,
    borderColor: "grey",
    borderWidth: 1.5,
  },
  cargoPicker: {
    width: "80%",
    backgroundColor: "white",
    borderColor: "grey",
    borderWidth: 1.5,
    height: 55,
    borderRadius: 5,
    marginVertical: 6,
  },
  btn_cadastro: {
    backgroundColor: colors.verde,
    padding: 10,
    borderRadius: 10,
    width: 130,
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 30,
  },
  text_cadastrar: {
    color: "white",
    fontSize: 17,
  },
  NomeSobrenome: {
    width: "80%",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  inputNomeSobrenome: {
    backgroundColor: "white",
    borderRadius: 5,
    padding: 10,
    marginTop: 20,
    marginBottom: 10,
    borderColor: "grey",
    borderWidth: 1.5,
    marginVertical: 6,
    width: "48%",
    fontSize: 16,
  },
  buttonsUser: {
    width: "80%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  btnFuncionario: {
    backgroundColor: colors.laranja,
    height: 47,
    width: "50%",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#975B26",
    borderWidth: 1.5,
  },
  btnCliente: {
    backgroundColor: colors.azul_claro,
    height: 45,
    width: "45%",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.primary,
    borderWidth: 1.5,
  },
  containerSelectClient:{
    width:300,
    marginLeft:55
  }
});

export default styles;
