import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
      },
      modalContent: {
        height: 450,
        width: 350,
        backgroundColor: '#ebebeb',
        padding: 20,
        borderRadius: 10,
        elevation: 15,
        alignItems: 'center',
        borderColor: '#083C52',
        borderWidth: 1,
      },
      title:{
        color: '#083C52',
        fontSize: 25,
        fontWeight: 'bold',
      },
      inputTitulo: {
        height: 50,
        width: '100%',
        backgroundColor: 'white',
        borderRadius: 5,
        padding: 10,
        marginTop: 20,
        marginBottom: 10,
        borderColor: 'grey',
        borderWidth: 1.5,
      },
      inputDescricao:{
        height: 90,
        width: '100%',
        backgroundColor: 'white',
        borderRadius: 5,
        paddingBottom: 55,
        paddingLeft: 10,
        marginBottom: 10,
        borderColor: 'grey',
        borderWidth: 1.5,
      },
      inputDataHora:{
        height: 50,
        width: '100%',
        backgroundColor: 'white',
        borderRadius: 5,
        padding: 10,
        marginBottom: 10,
        borderColor: 'grey',
        borderWidth: 1.5,
      },
      inputStatus:{
        width: "80%",
        backgroundColor: "white",
        borderColor: "grey",
        borderWidth: 1.5,
        height: 55,
        borderRadius: 5,
        marginVertical: 6,
      },
      buttonContainer: {
        height: 50,
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
        borderRadius: 5,
      },
      btnAdd:{
        alignItems: 'center',
        justifyContent: 'center',
        height: 40,
        width: '60%',
        backgroundColor: 'white',
        borderRadius: 5,
        backgroundColor: '#00A148',
        borderColor: '#417C5C',
        borderWidth: 1.5,
      },
      btnCancel:{
        alignItems: 'center',
        justifyContent: 'center',
        height: 40,
        width: '38%',
        backgroundColor: 'white',
        borderRadius: 5,
        backgroundColor: '#C06F26',
        borderColor: '#975B26',
        borderWidth: 1.5,
      },
})
export default styles;